### ISSUE TITLE
Make Animania Salt useable in the NC Melter

### ISSUE THREAD

**Issue by chadlupkes** [EnigmaticaModpacks/Enigmatica2Expert#1946]
**Modpack version**
1.83

**Issue**
Can you make Salt from Animania Ore Dictionary with Salt from Mekanism?  Trying to find the fastest way to get salt for the Melter.

**Comment by NillerMedDild** [comment]
I'll look into it :)

**Comment by ReiDaTecnologia** [comment]
Yeah i agree, several mods add salt and each one have their way of crafting it, the easiest one to craft is from Pam (Pot + Water bucket/Flesh Water). Would be cool if existed only one way to create Salt so don't exist the issue of choosing (Most players would go to Pam's salt anyway as it is the best one).

**Comment by chadlupkes** [comment]
Pam's Water Filter with Woven Cloth works really well, similar to how Water mills can be used to generate a lot of Grid Power.  Stacking them in a tower seems to work great.

**Comment by NillerMedDild** [comment]
It already is oredicted, not sure why the Melter recipe isn't picking it up tbh.

**Comment by Nabbieshtron** [comment]
you can generate infinite water from pam craft  using auto crafter (that purple crafting table)

> **Modpack version** 1.83
> 
> **Issue** Can you make Salt from Animania Ore Dictionary with Salt from Mekanism? Trying to find the fastest way to get salt for the Melter.

You can make infinite salt using autocraft table (purple crafting table lol) just put one pam craft water bucket and make a loop to get infinite water than use another auto craft tier 3 to craft salt  if you interested i can make a short vid for you lol
