### ISSUE TITLE
Forestry Carpenter only accepts regulary oak logs to make impregnated sticks?

### ISSUE THREAD

**Issue by toastonrye** [EnigmaticaModpacks/Enigmatica2Expert#1964]
### Modpack Version

1.83

### Describe your issue.

Spruce wood logs don't work, just the regular oak logs do, is this intentional?

### Have you modified the modpack?

No

### User Modifications

None.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.
