### ISSUE TITLE
Forestry Irradiated Comb has no output 

### ISSUE THREAD

**Issue by Nabbieshtron** [EnigmaticaModpacks/Enigmatica2Expert#1965]
### Modpack Version

1.83

### Describe your issue.

Forestry Irradiated Comb. It tells that you can put it in centrifuge but show no output and it wont let even put in centrifuge
![image](https://user-images.githubusercontent.com/56271010/136689786-fd612b68-903e-4521-8689-e33f33bd863e.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report. We didn't change those on purpose as far as I remember, but I'll investigate when I get time :)

**Comment by Krutoy242** [comment]
Btw, this fixed here https://github.com/NillerMedDild/Enigmatica2Expert/pull/1927
