### ISSUE TITLE
Fluid Dictionary Converter doesn't understand Oxygen

### ISSUE THREAD

**Issue by chadlupkes** [EnigmaticaModpacks/Enigmatica2Expert#1966]
### Modpack Version

1.83

### Describe your issue.

I know that some machines are supposed to accept NuclearCraft Oxygen and automatically convert it to Mekanism Oxygen, but it would be useful to be able to use the Fluid Dictionary Converter to do that transformation.  Right now, the block doesn't have Oxygen on the list.  Can we add it?

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
If you mean between liquid oxygen variants, then we ought to be able to do that, yeah :)

**Comment by Nabbieshtron** [comment]
same problem with hydrogen
