### ISSUE TITLE
Lycanites Mobs

### ISSUE THREAD

**Issue by YashTFEM** [EnigmaticaModpacks/Enigmatica2Expert#1987]
### URL

https://www.curseforge.com/minecraft/mc-mods/lycanites-mobs

### Why would you like the mod added?

It's a amazing mod that adds mob based tools and a whole bunch of hostile mobs and very hard, but rewarding dungeons. It also adds mob drops which can cast spells.  Tools are hard to craft since the materials are extremely rare, but the tools are amazing.

**Comment by YashTFEM** [comment]
Also adds mountable, creatures including flyers

**Comment by NillerMedDild** [comment]
I don't think this fits in E2E to be honest, so no :)

**Comment by YashTFEM** [comment]
I meant E6 not E2E

**Comment by YashTFEM** [comment]
I am pretty sure I selected E6 not E2E

**Comment by Frikkle** [comment]
This is the E2E issue tracker though ;-)

**Comment by YashTFEM** [comment]
:(
