### ISSUE TITLE
Modular Machinery Machine Controller Recipe Has Wrong Description For Circuit Boards

### ISSUE THREAD

**Issue by felixshiftellecon** [EnigmaticaModpacks/Enigmatica2Expert#1989]
### Modpack Version

1.83

### Describe your issue.

The enhanced circuit board in the modular machinery machine controller recipe has the wrong description. This is can be worked around with AE2 or manually placing the enhanced circuit boards, but if you don't modify the recipe auto crafting fails.

Description on the machine controller recipe: `Fits 1 electron tube.`

Description on the enhanced circuit board recipe: `Fits 2 electron tubes.`

Please see the attached pictures
![1 tube board](https://user-images.githubusercontent.com/57482070/149041979-95ffa076-4070-4362-ad27-0495d2d9e4f2.PNG)
![2 tube advanced](https://user-images.githubusercontent.com/57482070/149041984-66013684-879b-4c78-9b1b-0499c7f2e4e8.PNG)
![2 tube reg](https://user-images.githubusercontent.com/57482070/149041993-6a8aeb66-cb9d-4a64-9e2d-86cc37f5afe4.PNG)

### Crash Report

n/a

### Latest Log

n/a

### Have you modified the modpack?

Yes

### User Modifications

Optifine has been included

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by felixshiftellecon** [comment]
Thank you. Stumbled across a similar related issue.

The Intricate Circuit Board recipe in both the advanced and regular carpenter show the Enhanced and Refined Circuit Boards with a description of `Fits 1 electron tube.` when they should be `Fits 2 electron tubes.` and `Fits 3 electron tubes.` respectively.

**Comment by Discomanco** [comment]
This should actually be fixed with #1926
