### ISSUE TITLE
[Suggestion] Add Alumite to the Advanced Metallurgic Fabricator?

### ISSUE THREAD

**Issue by ReiDaTecnologia** [EnigmaticaModpacks/Enigmatica2Expert#1995]
### Describe your suggestion

Alumite are just like the other already added alloys so i always thought it was in the list but it wasn't...

### Why would you like this added/changed?

This is the reason why i'm suggesting this addition. I already added it manually so here is the code in case you are interested:
```
mods.modularmachinery.RecipeBuilder.newBuilder(machineName + "_alumite_ingot", machineName, 10)
	.addEnergyPerTickInput(100000)
	.addItemOutput(<ore:ingotAlumite>, 6)
	.addItemInput(<ore:ingotAluminium>, 5)
	.addItemInput(<ore:ingotIron>, 2)
	.addItemInput(<ore:obsidian>, 2)
	.build();
```

Up to you <3

**Comment by NillerMedDild** [comment]
Good idea, thanks for the code :D
