### ISSUE TITLE
[Suggestion] A simple mod to fix a certain issue with max life.

### ISSUE THREAD

**Issue by Terra-B-Welch** [EnigmaticaModpacks/Enigmatica2Expert#1996]
### Describe your suggestion

So theres a very simple mod that helps fix up a small issue involving some mods with items or perks that increase maximum life, the issue is every time the player logs back in those maximum life increases do not stay, requiring the player to waste food every time they relog in order to get their life back to full, this is notable with the ring of odin from botania and with astral sorcery perks that increase maximum life(mainly perks from the aevitas tree)

The mod in question is this one.
https://www.curseforge.com/minecraft/mc-mods/give-me-back-my-hp

All the mod does is fix the mentioned max life bug, nothing more.

### Why would you like this added/changed?

There's enough stuff the players gotta go through in this expert pack, it would be nice if wasting food to deal with a bug every login wasn't one of them! Especially with the nutrition mod!

**Comment by NillerMedDild** [comment]
Good idea, I'll add that in the next update 👍
