### ISSUE TITLE
Advanced Rocketry - Air vent not working in space station.

### ISSUE THREAD

**Issue by Terra-B-Welch** [EnigmaticaModpacks/Enigmatica2Expert#1998]
### Modpack Version

Version 1.83 for Minecraft 1.12.2

### Describe your issue.

Note: This is in multiplayer, I am not the server host.

When I first made a space station and set it up, I added in an oxygen vent, and proceeded to set up some machines and whatnot before I went to bed for the day, I checked to see if I was getting air, and I was in fact getting air, using two air vents and a CO2 Scrubber with cartridge.

I logged into the server today(it had restarted during the time I was sleeping) and despite having not modified anything on the space station, my workshop room no longer had air and was considered a vacuum. The air vents were still making noise as if they were working, but I know the vacuum wasnt a visual thing as I was in fact losing air.

As seen here, it says it's a vacuum despite it being airtight sealed blockwise. (Fused Quartz window btw, it's not a hole)
https://imgur.com/GM2YENX
https://imgur.com/DJHrKGZ

Also heres the area between the room and the outer shell, meant to allow for running conduits and cables without accidently losing air, but that apparently didn't work.
https://imgur.com/SWYWlKM

One last image of the exterior, there were no holes in the exterior, any I saw I patched up, but it made no difference.
https://imgur.com/84yR65w

I've also tried filling the cabling space to make the area smaller, and have even blocked off the air locks in the event the air lock doors bugged, no dice.

Unsure if it's related to this issue https://github.com/Advanced-Rocketry/AdvancedRocketry/issues/1485#issue-400931724

### Crash Report

N/A

### Latest Log

https://gist.github.com/Terra-B-Welch/94407e870c42d110980dbac42bca0b7b - This is my log, I am not sure if I can get the log from the server owner though.

### Have you modified the modpack?

Yes

### User Modifications

Technically yes, but only disabling the overworld render in advanced rocketry and applying the fuel fix from #1948 as well as tweaking some Astral Sorcery render settings, apart from that I did not touch anything else. I am also using optifine for a shader pack, but have the shader pack set up to disable in Advanced Rocketry dimensions(hence why there's no shaders in the images.)

It should be noted this issue occured after having the server owner apply the above fuel fix, I am not certain if the server owner modified anything else.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report. Advanced Rocketry issues are always tricky because we hardly ever get a response from them. 

I recommend that you ask the server owner for another restart, and verify with him that he hasn't changed anything other than made the fuel config fix.

**Comment by Terra-B-Welch** [comment]
Thanks for the response, I've left a message for the server owner to see, I think they're asleep currently but I'll let you know when I get an update on the situation.

**Comment by Terra-B-Welch** [comment]
I have verified, nothing else on the server owner's end was touched apart from the fuel thing.
Have asked the owner to do a manual restart, the server does auto-restarts daily, but idk if that helps it.

**Comment by Terra-B-Welch** [comment]
So I'm just taking a shot in the dark here, but perhaps updating advanced rocketry in the next E2E update will fix this issue? Wondering if this bug is exclusive to 2.0.0 build 250(the version of AR this modpack is using) and perhaps it was fixed in a later build?

**Comment by Terra-B-Welch** [comment]
So I was able to replicate the vacuum issue in singleplayer by rebuilding the ship workshop room in singleplayer. Looks like this bug isn't multiplayer exclusive.
https://imgur.com/GmMcDDt

I updated to the latest advanced rocketry builds in a copied version of the instance for testing purposes, the issue persists. Although in later versions I notice it having pressurized air for a moment before going back to vacuum.
https://imgur.com/0cw00Rq

I'll keep experimenting and figuring out if there's any way I can get the stubborn thing to give air.

**Comment by ReiDaTecnologia** [comment]
What if you put all the blocks that u used to build the ship in the AR "Should be sealable" config?

**Comment by Terra-B-Welch** [comment]
> What if you put all the blocks that u used to build the ship in the AR "Should be sealable" config?

I will give this a test in the test copy later, all I know is I did this test with a small space station made of iron blocks and glass, same issue.

**Comment by weeeeelp** [comment]
FYI, I had several issues with my Advanced Rocketry space station, including your exact issue with the vent, alongside with the AE2 Quantum Ring going offline after some time. The simplest solution is to **chunkload the station**, using whatever method you want (I used IC2's Chunk Loader). 
It would seem that the vent's "Online" state doesn't get correctly persisted in the chunk state upon unload/reload.

**Comment by Terra-B-Welch** [comment]
The thing is, using FTB utils I do have it chunkloaded, it didn't work.

**Comment by Terra-B-Welch** [comment]
> 

got around to testing this, it didn't work sadly, tested with a small room of vanilla iron blocks and glass.

I did notice that it has pressurised air for a short bit after activating it, but the moment the air vent starts making noise it goes back to vacuum.

**Comment by Terra-B-Welch** [comment]
So it turns out I'm and idiot and just did it wrong the entire time, I need 2 C02 collectors and 1 vent, not the other way around, I feel 2.0.0 made this change, but it's likely I'm an idiot.

This is now closed.

**Comment by Terra-B-Welch** [comment]
Ok nvm, apparently it needed time, I logged into the server, went into my space station, and the room had air.
