### ISSUE TITLE
[Suggestion] Computronics, an addon for ComputerCraft and OpenComputers

### ISSUE THREAD

**Issue by k00lk4t** [EnigmaticaModpacks/Enigmatica2Expert#1999]
### URL

https://wiki.vexatos.com/wiki:computronics

### Why would you like the mod added?

Adds a bunch of helpful stuff including a sound card for the computers that allows you to play midi level sounds, a lamp with up to 32768 colors, an audio player and more. I'd like this to be added mainly for the sound cards midi playing capabilities but it has more than just that.

**Comment by NillerMedDild** [comment]
We have plenty of Computer mods as it is imo 😄

**Comment by Anthonity** [comment]
NO MIDIS IN ENIGMATICA 2 EXPERT?
