### ISSUE TITLE
E2E Crashes on world load

### ISSUE THREAD

**Issue by Tray3600** [EnigmaticaModpacks/Enigmatica2Expert#2001]
### Modpack Version

1.83

### Describe your issue.

It loads, says building terrain, then shutting down internal server and crashes after around 10 seconds.
I have tried restarting my computer and downgrading to forge 1.12.2.14.23.5.2768, but that didnt work.

### Crash Report

https://gist.github.com/Tray3600/cb7dad98d9729fe1fd83f922b3711a32

### Latest Log

https://gist.github.com/Tray3600/a2e5f29747046927c56627bca96835cf

### Have you modified the modpack?

Yes

### User Modifications

I have disabled foamfix and re enabled it but that did not work.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by KacproPL132** [comment]
Try downgrading java to 311 or 312 :D
321 is known to have a lot of problems with minecraft.

**Comment by Tray3600** [comment]
Does not work
[Crash Report](https://gist.github.com/Tray3600/e5af4cac1a40b5aa2f978bcb5ff106f8)

**Comment by KacproPL132** [comment]
Well crashlog reports that you are still using 321.

**Comment by HopeNotDespair** [comment]
Make sure you delete java
Control panel-->Programs-->Uninstall programs-->Search for java, right click, then uninstall

**Comment by Tray3600** [comment]
Crashed again
[Crash report](https://gist.github.com/Tray3600/5f937cab724bfd36032da78603d1fd45)

**Comment by HopeNotDespair** [comment]
Thankfully, it's not a java crash anymore

**Comment by Tray3600** [comment]
No, I do not.

**Comment by Discomanco** [comment]
Then I recommend you get one. That should fix your problem too.

**Comment by Tray3600** [comment]
I do not have the money for that, I would if i could.
Also, i forgot to mention: The mod pack used to work 2 days ago but yesterday it stopped working

**Comment by Discomanco** [comment]
That's too bad, unfortunately we do not offer support for cracked clients.
If you still have a problem after acquring a legitimate account at some point, you can of course ask again.

**Comment by ReiDaTecnologia** [comment]
Just wanted to report that this crash happened with me, even tho i have a mc account. It only happened once and it still didn't happen to me again.
