### ISSUE TITLE
Unlimited Chisel Works recipes for alabaster are unobtainable

### ISSUE THREAD

**Issue by MatthiasPortzel** [EnigmaticaModpacks/Enigmatica2Expert#2002]
### Modpack Version

1.83

### Describe your issue.

Alabaster bricks can be chiseled into Alabaster and only 2 other things, both from Environmental Materials (I think is the name of the mod).

But Unlimited Chisel Works adds a lot of variants of Alabaster that are unobtainable as far as I can tell. I have some of them left over from an earlier version of the pack, and I can chisel them back into normal Alabaster, but then can't get them back; it's a one-way recipe.
<img width="499" alt="UCW Alabaster double slabs has 37 chisel options" src="https://user-images.githubusercontent.com/19734415/152463820-43863405-c8a7-4ad1-b4fb-fa408eba3032.png">

<img width="518" alt="Alabaster Bricks have 4 chisel options " src="https://user-images.githubusercontent.com/19734415/152464013-53211c0e-690e-4bdc-8f61-f6394cbb77f3.png">

Interestingly, looking at JEI for Alabaster Bricks, it shows a "second page" with more options, but since Chisel, of course, only shows one page, only the first 4 options are actually available.

<img width="445" alt="Chisel Alabaster bricks has two pages in JEI" src="https://user-images.githubusercontent.com/19734415/152464176-0910693b-31da-436b-b62b-027a10c87782.png">

To speculate a bit, I think in previous versions of the pack, Alabaster couldn't be chiseled into Alabaster bricks, and I suspect adding that chisel recipe (Alabaster -> Alabaster Bricks) broke the other ones (Alabaster/Alabaster Bricks -> UCW Alabaster).

I know you've closed several chisel bugs in the past so I understand if this isn't high priority.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by SteaSteaStea** [comment]
From what I've seen almost everything from the unlimited chisel works mod is unobtainable in this modpack.

**Comment by NielsPilgaard** [comment]
> From what I've seen almost everything from the unlimited chisel works mod is unobtainable in this modpack.

Really? I haven't spotted anything that can't be crafted in version 1.85
