### ISSUE TITLE
Crash on Startup with newer java 8 version

### ISSUE THREAD

**Issue by JLS-cs** [EnigmaticaModpacks/Enigmatica2Expert#2011]
### Modpack Version

1.83 Client

### Describe your issue.

Game crashes on Startup
found another thread from another github that points to newer java versions and "old" modloaders being the cause, but i could be totally wrong here.
https://github.com/itzg/docker-minecraft-server/issues/1325

Java Version is: Java 8 Update 321

### Crash Report

https://gist.github.com/JLS-cs/74b89c4ca9d2fefa3985f62ffb65e941

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Discomanco** [comment]
"Native path:
  D:/MultiMC/instances/Enigmatica 6 - E6 - 1.16.5/natives"
  
You might want to double check the profile you're launching :V

**Comment by JLS-cs** [comment]
problem was on my end, had 2 multimc installs, one with an 2021 version of E6 that i didnt update and a new install with E2E but i accidently opened the older one since windows randomly started showing the older one first when searching for it.
sorry for wasting any time if i did.

**Comment by NillerMedDild** [comment]
No worries :)
