### ISSUE TITLE
update immersive tech to a supported fork

### ISSUE THREAD

**Issue by wec22** [EnigmaticaModpacks/Enigmatica2Expert#2012]
### URL

https://www.curseforge.com/minecraft/mc-mods/mct-immersive-technology

### Why would you like the mod added?

the current version of immersive tech has not been updated in a while.  the project has effectively been removed from curseforge.  when trying to install the pack using a 3rd party launcher (i.e. GDLauncher) the mod is not found and is not grabbed.  the new fork is endorsed by the previous maintainer and is regarded as the official continuation.  a potential con would be the new multiblocks which would require additional tweaking, but they could also be disabled if needed.  The new fork also adds crafttweaker support which I can imagine would be useful for the pack devs.  

Also adds advanced rocketry integration which could provide some interesting gameplay opportunities.

Also adds JEI support to IT machines.

**Comment by NillerMedDild** [comment]
I guess we have to :/ thanks for the suggestion.
