### ISSUE TITLE
there is too much magic please make a holy version

### ISSUE THREAD

**Issue by electrolys** [EnigmaticaModpacks/Enigmatica2Expert#2017]
### Describe your suggestion

i am too holy for your modpack please make a better version
some suggestions nothing that has a reference or are similar to blood, magic, witchcraft, or souls (for mods that are not highly focused on this you can just remove the items that are this way and hide them in jei)
dragons are alright as they are in the bible (kind of)
nothing really dark in nature

### Why would you like this added/changed?

me and my friends are too holy for thy modpack

(this idea for a magicless modpack is only partly a joke)

**Comment by NillerMedDild** [comment]
We'll consider it for the next expert pack :P
