### ISSUE TITLE
Crash on world load after PC crash during gameplay

### ISSUE THREAD

**Issue by MertX2** [EnigmaticaModpacks/Enigmatica2Expert#2020]
### Modpack Version

1.83

### Describe your issue.

I was working on crafting Terrasteel ingots when my PC suddenly froze out of nowhere, causing me to reset it. After then starting the modpack again and trying to load a world Minecraft crashes.
No crash report was generated.

Using MultiMC with the recommended JVM arguments from this guide:https://gist.github.com/NillerMedDild/40b4992b7a3e5e653a353fe1d45f2185
and allocated 6700mb of RAM.

### Latest Log

https://gist.github.com/MertX2/5361980e16766b365c7d395b127921c7

### Have you modified the modpack?

Yes

### User Modifications

Added VanillaFix and updated Animania to 1.0.2.28 to fix another crash involving the Thermal mods. Was fine for about 80h of gameplay.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
I recommend that you remove VanillaFix, thats likely the issue :)
