### ISSUE TITLE
E2E server Crashing Because of Something in the world

### ISSUE THREAD

**Issue by JensDeLeersnyderPXL** [EnigmaticaModpacks/Enigmatica2Expert#2022]
### Modpack Version

1.83

### Describe your issue.

First the Server starts and then after a bit it crashes I think a machine is causing the issue, but can't find out from the crash log what .

### Crash Report

https://gist.github.com/JensDeLeersnyderPXL/95bb1a37740ade689b64db8e3dde11be

### Latest Log

https://gist.github.com/JensDeLeersnyderPXL/50628b06e29b7819a3b8cec60fe87993

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by JensDeLeersnyderPXL** [comment]
I think I found the issue, I was autocrafting ultimate induction providers with AE2.  All the energy tablets 1000+ and energy cubes were making the server crash.

**Comment by ReiDaTecnologia** [comment]
> I think I found the issue, I was autocrafting ultimate induction providers with AE2. All the energy tablets 1000+ and energy cubes were making the server crash.

It is because of the WatchDog timer, set it to -1 (To disable it) or a high number.

**Comment by tuca1234567890** [comment]
> I think I found the issue, I was autocrafting ultimate induction providers with AE2.  All the energy tablets 1000+ and energy cubes were making the server crash.

Disable substitution on all of your induction provider, induction coil and energy tablet crafts and manually fill in the recipes instead of pressing the + on JEI
