### ISSUE TITLE
/dank/null duplication bug

### ISSUE THREAD

**Issue by FirstTimeGaming** [EnigmaticaModpacks/Enigmatica2Expert#2031]
### Modpack Version

1.83

### Describe your issue.

Dropping any verison of the dank nulls and opening them in quick succession, pressing Q and shift right clicking, at very close intervals allows you to take items out of the dank null without actually taking them out of the dank null when you pick it up off the ground again

Solution: updated dank null to beta 1.7.101

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
Thanks for the report.

Updating to that version deletes all existing Dank Nulls, no?

**Comment by Krutoy242** [comment]
> Updating to that version deletes all existing Dank Nulls, no?

Yes. NBT tags would be changed. Technically, old DankNull content would stay here, but not read correctly.

**Comment by NielsPilgaard** [comment]
Thanks Krutoy :)

I'm afraid that's simply too breaking, we'll have to live with the dupe bug. It's one of many after all 😄
