### ISSUE TITLE
Disable certain Mineral Deposits for IE Excavator

### ISSUE THREAD

**Issue by DavidckPixel** [EnigmaticaModpacks/Enigmatica2Expert#2032]
### Describe your suggestion

Remove certain (all) Mineral Deposits from the current Immersive Engineering Excavator List.
Mineral Deposits suggested for removal:
  -Bauxite (Aluminum, Rutile)
  -Platinum (Platinum, Nickel, Iridium)
  -Nickle (Nicke, Platinum, Iron)

### Why would you like this added/changed?

In its current state, IE Excavators allow for the gathering of an insane amount of Ore with very little power requirement, compared to other Automated Miners (such as the void miner).

The 3 Mineral Deposits stated above give ores which should only be obtainable (in large quantities) during a later stage. Rutile, which can very easily be turned into Titanium, while the tool tip for Titanium sais it is obtained through an Advanced Metallurgic Fabrication.

**Comment by NielsPilgaard** [comment]
This is intended behaviour :)
