### ISSUE TITLE
Advanced carpenter structure not found

### ISSUE THREAD

**Issue by giodav2015** [EnigmaticaModpacks/Enigmatica2Expert#2033]
### Modpack Version

1.83

### Describe your issue.

I was building the advanced carpenter and it said structure not found, so i rebuilt it 3 times in an other world too and still not building. Then i used the phantom guide of the blueprint and it solved, but the guide cannot rotate. So i'm forced to built it in the direction that the blueprint says. Pls fix.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
The structure cannot be rotated, I would have to make 4 distinct Advanced Carpenters to be able to rotate them, and I think it would be confusing with 4 versions in JEI.
