### ISSUE TITLE
E2E - Dilithium and Rutile ores spawning in the overworld, bug?!

### ISSUE THREAD

**Issue by GrimReaper1982** [EnigmaticaModpacks/Enigmatica2Expert#2034]
### Modpack Version

1.83

### Describe your issue.

Iam currently playing Enigmatica 2 Expert for a third round. As i started to mine for ores to get my first advanced tools, i just found spawns of Rutile and Dilithium in die normal Overworld dimmension. My last playtrough was with version 1.78 and both ores did not spawn in the overworld. You may have found them in the Twilight Forest here and there in small quantities, but never seen them in the overworld.

So i guess this is a bug in 1.83? Didn`t find any Bug Reports about it here.

Can you tell me if this is in fact a bug or is it a new "feature" from the version 1.83?
If you don`t want to fix it, maybe you can tell me where to find the exact config file for the ore spawn,
so i can fix it myself?

i already found some entrys in -> config\cofh\world16_advanced_rocketry_planets_ore.json but both ores
are not whitelisted for the overworld, see this (cut out) entrys please:

		"rutile": {
		
			"dimension": {
				"restriction": "whitelist",
				"value": [
					106,
					111,
					112,
					114,
					121,
					123
				]
			}
		},
		"dilithium": {
			
			"dimension": {
				"restriction": "whitelist",
				"value": [
					100,
					105,
					108
				]
			}
		},
		"rutile_moon": {
			
			"dimension": {
				"restriction": "whitelist",
				"value": [
					100,
					105,
					108

I tested this with a fresh install of the version 1.83, same behavior.

Thank you very much in advance for any reply on this.

### Have you modified the modpack?

Yes

### User Modifications

i just tweaked the two configs for Draconic Evolution and Advanced Rocketry a bit for my needs:

Draconic Evolution:
- reactor only explodes as "TNT" not that giant apocalyse BooM :)
- chaotic islands spawn in every other 4k blocks instead of 10k each
- chaotic guardian does not kill creative players

Advanced Rocketry:
- Oxygen Vents use volume math instead of fixed block ranges

Tweaks where made since Modpack Version 1.78 and didn`t have any other impact/conflict

### Did the issue happen in singleplayer or on a server?

Both

**Comment by GrimReaper1982** [comment]
Hey Niller,

i did not found the ores in geodes. They spawned in normal caves near the entrance, Y-level approx ~50-55 for the rutile
and deeper. The Dilithium ores are found a bit deeper while digging out some coal/copper ones that generated right in front.

i can provide the world seed if needed and the coords for the cave entrance, if you want?

By the way: Thank you very, very much for this great modpack. I love it so much <3

Have a great evening.

Kind regards.

**Comment by GrimReaper1982** [comment]
as to mention:

I discovert that much more ores spawn from Vulpes library instead of Thermal Foundation ores since 1.83,
maybe since 1.82a?.
I do remember only finding Vulpes ores in the Twilight Forest here and there but mostly Thermal Foundation
variants. Now it seems like ~30% of the ores that generate even in the overworld are those from Vulpes.
Found Copper ores from both mods. Tin only from Vulpes so far... But iam still very early game ;) Maybe 4 hours
in now.


Maybe this is a critical hint for you to find out whats going on.

**Comment by tuca1234567890** [comment]
Corrupt modpack install? Pretty sure I never found VulpesLib ores in the overworld and Thermal Foundation ores spawn normally. My version is also 1.83. Can't test right now, as my main computer is broken.

**Comment by NielsPilgaard** [comment]
That does indeed sound like a corrupt install, I recommend reinstalling and having a look in a new world.

**Comment by GrimReaper1982** [comment]
Heyho!

My current savegame is running on a fresh E2E 1.83 automated installation on a rented server.
I have a fresh second installation of E2E 1.83 here and got the seed from the hosted server world.

I recreated the world using the seed with the fresh installation. And guess what happend...?
Same coords, same cave... no Dilithium, no Rutile.

No things get a bit wild:

With my "regular" E2E 1.83 installation and the seed, i got Dilithium and many Vulpes ores again...
The Worldgen does even wilder things: a big crater from AE2 that was filled with lava around the
skystone core was empty in this installation. The crater was there, the skystone meteroite too, but
the lava was gone.

Seems you`re right, and somehow... in a way i can`t figure out, my installation seems in fact a bit corrupt.
And thats the same thing for the hosted server.

I guess i have to reinstall both and start a new savegame then. Glad i only played this save for a couple of
hours now.

Well, problem solved. Many thanks for the feedback! Whould not have figured out that my installation is
actually broken.

Wish you both a nice weekend.

Kind regards.

**Comment by GrimReaper1982** [comment]
Ok i figured it out.

after much testing with the clean installation, overwriting the mods folder and all the other stuff,
i can reproduce the error. The config from Advanced Rocketry was the problem. After switching to
the original from a fresh install, the world generated normally without the Rutile and Dilithium ores.

And iam very sure now why this occured.

I`ve been playing my second E2E attempt savegame nearly a year+ ago in Version 1.78 or 1.81.
Don`t know it exactly, but at least 1.78. After updating the modpack during last year and jumped
back into this savegame, i had some issues with Advanced Rocketry: Every multiblock machines
didn`t work anymore. The problem was very clear: because of an updated mod-version from the E2E Update,
the multiblock designs where changed a bit here and there, and i had to fix the missing parts/exchange some
of the components completly. After that, my multiblock machines where running again.

The problem must have occured when i pasted my backuped config for Advanced Rocketry in the new Profile with
the updated E2E installation. As mentioned i changed the math for the oxygen-vents to volume and i didn`t want
to find the settings and editing them again. So i used the old config file. I even uploaded it to the hosted server.

So, i finally found the solution, maybe this helps someone in some day... :)

Kind regards.

**Comment by NielsPilgaard** [comment]
Ah yes, the Advanced Rocketry config has changed quite a bit between 1.78 and 1.83, the mod is expecting different things in there.
