### ISSUE TITLE
AE2: Unofficial Extended

### ISSUE THREAD

**Issue by Craosien** [EnigmaticaModpacks/Enigmatica2Expert#2045]
### URL

https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life

### Why would you like the mod added?

Maybe if theres ever going to be a new update for E2E switch out AE2 with AE2 Unofficial Extended? The mod has a lot more QoL, its more finished and is still maintained.

**Comment by NielsPilgaard** [comment]
I'd rather not spend my time making the switch tbf.

**Comment by jlfree12** [comment]
I was able to just replace regular AE2 with this and had absolutely no issues playing the pack. I think you are overestimating the effort required to actually make the switch, unless you mean in terms of recipes (even then it doesn’t add that many). The QOL this version of AE provides is huge, I think you should reconsider.

**Comment by King65868** [comment]
You just replace old ae2 and JEE with the fork, it does add a few items which you would have to look at I guess as well though

**Comment by NielsPilgaard** [comment]
Switching mods is super simple, but there's a ton of things I need to validate to ensure I don't mess up existing worlds. I don't want to make that investment, I'd rather spend my time on E6E and E9.
