### ISSUE TITLE
mattock break blocks not drop

### ISSUE THREAD

**Issue by ChargeElectrum** [EnigmaticaModpacks/Enigmatica2Expert#2046]
### Modpack Version

1.83

### Describe your issue.

i have a Manyullyn - alumite mattock (manyullyn axe head - alumite shovel head) and i try to break dirt and grass it dropped nothing also with logs oak and acacia. i tried upgrade head to osglogas and it still not working

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Alumite lets you bind your tool to an inventory, the blocks you break go into that inventory :)
