### ISSUE TITLE
[Mod Suggestion] Framed Compacting Drawers

### ISSUE THREAD

**Issue by tuca1234567890** [EnigmaticaModpacks/Enigmatica2Expert#2048]
### URL

https://www.curseforge.com/minecraft/mc-mods/framed-compacting-drawers

### Why would you like the mod added?

Makes Compacting drawers, drawer controllers/slaves frameable.

**Comment by NielsPilgaard** [comment]
I don't plan on making another content update for E2E, if I do I'll consider adding this :)

**Comment by tuca1234567890** [comment]
Now that a content update is on the horizon, would you reconsider?

**Comment by NielsPilgaard** [comment]
I'll have another look :)
