### ISSUE TITLE
Mekanism Ultimate Fluid and gas tanks are broken for crafting

### ISSUE THREAD

**Issue by Cooper1dog** [EnigmaticaModpacks/Enigmatica2Expert#2053]
### Modpack Version

1.85

### Describe your issue.

When trying to craft things in the AE2 system, the system does not recognize Mekanism Ultimate tanks. Even the known workaround of crafting a tank and adding it into the recipe for the proper ID is not working.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Shen Bapiro#3141

**Comment by NielsPilgaard** [comment]
Im fairly certain I fixed this in-dev last night 👍

As a workaround while you wait, you could try placing down the tank/gas tank and then use it in recipes, and see if AE recognises that.

**Comment by Cooper1dog** [comment]
Placing the tanks down works! Thanks for the advice while I wait.

**Comment by Cooper1dog** [comment]
The issue appears that it may extent to Lapotron crystals as well.

**Comment by NielsPilgaard** [comment]
Hmm are you sure? All occurrences of it are using `.anyDamage()` which means NBT is ignored.

**Comment by Cooper1dog** [comment]
I apologize. I deleted my post.  The Chemical Crystallizer appears to require a fully charged Lapatron. I was confused because the charge in the recipe is 0 but it only accepts a fully charged crystal. I see the indicator on the crystal for that recipe is green indicating full charge.

**Comment by NielsPilgaard** [comment]
All good 👍
