### ISSUE TITLE
CTD when crafting furnaces

### ISSUE THREAD

**Issue by richtigerfeger** [EnigmaticaModpacks/Enigmatica2Expert#2054]
### Modpack Version

1.82a

### Describe your issue.

When I craft a furnace the game crashes to desktop. It happened three times in a row and is thus repeatable.

### Crash Report

<script src="https://gist.github.com/richtigerfeger/a0966864c537484234ca4c9cc0399c2a.js"></script>

### Have you modified the modpack?

Yes

### User Modifications

Optifine, PureBDCraft Texture pack

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
It seems the crash report didn't load properly, could you please re-attach it? :)

**Comment by richtigerfeger** [comment]
Hassn't crashed anymore after I posted this. I guess complaining resolved the issue. Maybe something with the new java update or something

**Comment by richtigerfeger** [comment]
[2022-10-24-4.log.gz](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/files/9852472/2022-10-24-4.log.gz)
[latest.log](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/files/9852473/latest.log)
It happened again, this time when I was gonna craft pistons. Seems to be something with dense cobblestone

**Comment by NielsPilgaard** [comment]
Please try without Optifine :)
