### ISSUE TITLE
Unable to craft items requiring IC2 Energy Crystals and Nanosuit Boots

### ISSUE THREAD

**Issue by Carboxcide** [EnigmaticaModpacks/Enigmatica2Expert#2055]
### Modpack Version

1.85

### Describe your issue.

I currently can't craft the Nanosuit Boots or the Flux Infused Boots, the recipe simply doesn't work. This was tested for the following  cases: Nanosuit Boots with both a freshly crafted energy crystal and a fully charged energy crystal; Flux Boots with both un-charged (but looted) nanosuit boots and fully charged nanosuit boots. This was also cross-tested by other members of the discord.

Crafting the Quantum Boots with a fully charged lapatron crystal and looted flux boots works.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Carboxcide#5672

**Comment by lekutree** [comment]
I was able to get the boots to craft by giving an energy crystal 1 durability. Which is what it shows in JEI, so its definitely an NBT issue

**Comment by lekutree** [comment]
This will likely affect anything with an energy crystal or lapotron crystal in the recipe

**Comment by NielsPilgaard** [comment]
I've managed to make the recipes work when the items are charged, that might be the best I can do unfortunately.

**Comment by lekutree** [comment]
> I've managed to make the recipes work when the items are charged, that might be the best I can do unfortunately.

That's not so bad. If it's reflected in JEI, it just adds another step to autocrafting

**Comment by NielsPilgaard** [comment]
I got it working properly \o/ any level of energy is accepted, including full and none.
