### ISSUE TITLE
Client closes right after connecting to E2E server - v1.85

### ISSUE THREAD

**Issue by filcobra** [EnigmaticaModpacks/Enigmatica2Expert#2060]
### Modpack Version

1.85

### Describe your issue.

I had more than 40 hours playing in this server with no issue. 
Then one day, after loading and right after connecting to the server the client exits. This has been going on for two days now and I couldn't ever come back to the game. I tried reinstalling the modpack and even curseforge several times. I tried allocating 9GB, 10GB and even 12GB of RAM.
Nothing seems to explain what's going on. Right after I log into the server, the client closes.

### Crash Report

https://gist.github.com/filcobra/610a12fbb8db9c68605e47ec4c9c1044

### Latest Log

https://gist.github.com/filcobra/6c3dbb8ea3de0bcf3dea60419b1bd689

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Filcobra#5957

**Comment by NielsPilgaard** [comment]
I'm afraid I don't see anything in those logs, not even you being disconnected. Are you sure they're the right ones?

**Comment by filcobra** [comment]
Hi, let me add the hs_err_pid log file of the same time the crash ocurred. Maybe it will tell more about it:
[hs_err_pid12332.log](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/files/9943017/hs_err_pid12332.log)

**Comment by NielsPilgaard** [comment]
That's very helpful, thanks. Seems like the Java version bundled with CurseForge is causing this issue - The fix would be to force CurseForge to use a more recent version of Java 8.
