### ISSUE TITLE
error joining server

### ISSUE THREAD

**Issue by DarknessAwakensYT** [EnigmaticaModpacks/Enigmatica2Expert#2063]
### Modpack Version

1.37

### Describe your issue.

![Screenshot_4](https://user-images.githubusercontent.com/33302726/200403449-0ee80bf2-5f0b-468c-be4f-63c486af4eb5.png)

this happens every time i try to join my server

doesnt happen in a new world just on the server

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

frxstdemon#9258

**Comment by NielsPilgaard** [comment]
Errr.. Version 1.37? Are you sure?

**Comment by Kanzaji** [comment]
@NielsPilgaard Check contributor chat, It seems that this is an issue with CurseForge 😅It was happening to MorganSimic and few others on support as well.
