### ISSUE TITLE
Latest update broke crafting changes

### ISSUE THREAD

**Issue by DezRexy** [EnigmaticaModpacks/Enigmatica2Expert#2064]
### Modpack Version

1.86

### Describe your issue.

After installing the newest update, all crafting recipes seem to have been reverted to vanilla. This occurs on old and new worlds. I've tried reinstalling the modpack, reverting back to the previous version, and changing just CraftTweaker2 back to its previous version on the current modpack version as I saw that it had been updated. Other than that last change, nothing about the modpack has been altered, and the errors occurred even before I had attempted that.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Gcat101** [comment]
It's a cf launcher issue, not an enigmatica issue.

**Comment by tuca1234567890** [comment]
Not an issue with the pack, the CurseForge launcher broke and these recipes are a result of that.

**Comment by Kanzaji** [comment]
@DezRexy you can try out MultiMC (can't download packs however, but can import them from FTB app), FTB APP, GD Launcher or AT Launcher :D

**Comment by Gcat101** [comment]
Prism also

**Comment by ReiDaTecnologia** [comment]
PolyMC? it's basically MultiMC but with the ability to install and update mods.

**Comment by Kanzaji** [comment]
PolyMC had a huge drama recently. Prism is fork of Poly.
I... dont trust both anymore tho ^^"

**Comment by Gcat101** [comment]
Prism is the new poly fork

**Comment by tuca1234567890** [comment]
> > Not an issue with the pack, the CurseForge launcher broke and these recipes are a result of that.
> 
> 
> 
> > It's a cf launcher issue, not an enigmatica issue.
> 
> Ah, I see. Are there any other launchers I could possibly use to fix this, or am I effectively stuck with it until it's fixed?

PrismLauncher is pretty good imo, it's what I use
There's also ATLauncher, GDLauncher and the FTB App

**Comment by DezRexy** [comment]
> PrismLauncher is pretty good imo, it's what I use There's also ATLauncher, GDLauncher and the FTB App

I'll try PrismLauncher as soon as I can. As it stands right now I can't seem to sign into ANY launcher. Not sure why. Likely has correlation with the normal Minecraft launcher repeatedly saying it can't verify what I own.

**Comment by ReiDaTecnologia** [comment]
> > PrismLauncher is pretty good imo, it's what I use There's also ATLauncher, GDLauncher and the FTB App
> 
> I'll try PrismLauncher as soon as I can. As it stands right now I can't seem to sign into ANY launcher. Not sure why. Likely has correlation with the normal Minecraft launcher repeatedly saying it can't verify what I own.

did u made the account migration?

**Comment by DezRexy** [comment]
UPDATE: Tried it with the ATLauncher and I had to go into Microsoft EDGE for it to work?? No idea how that works but oh well. Thanks to everyone for your help!
