### ISSUE TITLE
Recipes changed to normal engimatica 2 recipes

### ISSUE THREAD

**Issue by giobiba** [EnigmaticaModpacks/Enigmatica2Expert#2065]
### Modpack Version

1.84

### Describe your issue.

I updated the version from 1.81 to 1.84 and the recipes are non expert. Tried creating a new safe and the recipes were non expert as well

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Kanzaji** [comment]
@giobiba This is CurseForge launcher issue. Should be already fixed in latest update of the launcher. Nothing to do with the modpack 😅

**Comment by giobiba** [comment]
@Kanzaji i don't think it has to do with curseforge, on a clean install of 1.86 the recipes are non-expert, while on a clean install of 1.80 they are expert. 🤷

**Comment by Kanzaji** [comment]
it was confirmed to be an issue with it 😅A lot of people fixed that with using different launcher / Waiting for a fix from CurseForge #2064 #2063 and support channel on Enigmatica server confirms that :P
Try out fresh 1.86, and if problems still appears (even on updated launcher), go to the support channel on discord :D

**Comment by giobiba** [comment]
Oh got it, I thought CF couldn't have such impact on the modpack. Thanks for the help :D!
