### ISSUE TITLE
Modular Machinery:Unable to use blueprint normally

### ISSUE THREAD

**Issue by ChouTreeMan** [EnigmaticaModpacks/Enigmatica2Expert#2066]
### Modpack Version

1.81a

### Describe your issue.

Modular Machinery:
cannot find any blueprint in JEI, but I can still produce any of it.
At the same time, all multi-square structures cannot take effect, and the products(like titanium ingot) produced by structures have no recipe.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by ChouTreeMan** [comment]
the name of all the blueprint are "null";
the file folder - ..\Enigmatica2Expert\config\modularmachinery\recipes is empty,is it normal?

**Comment by ReiDaTecnologia** [comment]
Are you using curseforge launcher? if yes: it is an issue with the launcher itself (so it affect all packs) update your launcher or use another launcher like GDLauncher or Prism.

**Comment by ChouTreeMan** [comment]
well，I’m using the latest HMCL which is a third-party launcher and stands for "Hello Minecraft! Launcher", and the forge version is 14.23.5.2860. I‘m confused about whether modpacks does not support third-party launcher. Maybe using a third-party launcher will cause multiple unknown bugs.

**Comment by NielsPilgaard** [comment]
I'm not familiar with that launcher, but it could be causing issues. Can you switch to CurseForge and try again?

**Comment by ChouTreeMan** [comment]
I finally fix this bug by upgrading the modpack version（1.81a -> 1.82）
Thank you for answering my questions！:>
