### ISSUE TITLE
Blood Magic Rune of Sacrifice recipe not recognized in Vanilla crafting table, not crafting in crafting station.

### ISSUE THREAD

**Issue by Nynne710** [EnigmaticaModpacks/Enigmatica2Expert#2067]
### Modpack Version

1.86

### Describe your issue.

Attempting to create a Rune of Sacrifice in a vanilla crafting table does not recognize the recipe as valid.

![Enigmatica 2_ Expert 11_10_2022 4_18_34 AM](https://user-images.githubusercontent.com/117905568/201065588-393177b6-e786-477c-9048-ee7894b8c2ca.png)

Unsure if it is because the crystal sword has a different attack damage amount.

![Enigmatica 2_ Expert 11_10_2022 4_19_13 AM](https://user-images.githubusercontent.com/117905568/201065859-d8697fee-a620-4ced-b703-91cd4c105674.png)

![Enigmatica 2_ Expert 11_10_2022 4_23_21 AM](https://user-images.githubusercontent.com/117905568/201066114-6f19216a-860f-46d5-904a-45d502f82dda.png)

Trying the recipe in a crafting station does recognize it.

![Enigmatica 2_ Expert 11_10_2022 4_20_28 AM](https://user-images.githubusercontent.com/117905568/201066770-81ff299f-65c8-4657-a83e-f2c4d375c49c.png)

However, the finished runes will not stay in player inventory. Shift + Right click will allow the runes to enter the player inventory, but any attempt to move them will cause them to disappear and the crafting materials to return to the crafting station, like they were never crafted. Attempting to drag the completed runes into an inventory will reset the recipe in a similar manner. If the runes are Shift + Right clicked onto the hotbar and then attempted to be placed in the world, they appear for a fraction of a second, and then disappear.

https://user-images.githubusercontent.com/117905568/201069457-dc49b8ed-835c-4c87-ac41-5c1df46b0db5.mp4

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Booti#8528

**Comment by NielsPilgaard** [comment]
Sounds like the server is on version 1.85 :)

**Comment by Nynne710** [comment]
Server updated, problem fixed.
