### ISSUE TITLE
Arms and Legs spasming out of control

### ISSUE THREAD

**Issue by cookiesurvival** [EnigmaticaModpacks/Enigmatica2Expert#2074]
### Modpack Version

Enigmatica2Expert-1.85

### Describe your issue.

Wish I knew what exactly caused this. But when I loaded up into my singleplayer world, my screen was tilting extremely to the right whenever I went in any direction other then jumping. Then I checked my inventory and realize my character's arms are spasming out of control. Whenever I move, I notice that my legs spasm out of control as well. Then I notice that some of my cows also have their legs spasming out, but I cant find a source of the constant spasming. Ill show a screenshot of what I have to see if it gives you guys any ideas. I also have a nether portal, small wheat and cow farm, and a basic coke oven.
![2022-11-17_17 08 53](https://user-images.githubusercontent.com/67572356/202570771-6f56ec3a-e339-42bb-8fae-bae5a70ee8a8.png)

### Crash Report

N/A

### Latest Log

https://gist.github.com/cookiesurvival/04c0704b2c06190004eccbf0fd965e09

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Cookiesurvival#2538

**Comment by ReiDaTecnologia** [comment]
Iirc that is caused by one of the BetterFPS' algorithms, try changing to a different one.

**Comment by cookiesurvival** [comment]
> Iirc that is caused by one of the BetterFPS' algorithms, try changing to a different one.

I've tried going back to the default one and everything works perfectly fine again. Thanks for the advice.

Warning that Taylor's Algorithm causes the effects explained above.
