### ISSUE TITLE
AE2 Fluid Crafting Rework

### ISSUE THREAD

**Issue by Knifepony** [EnigmaticaModpacks/Enigmatica2Expert#2075]
### URL

https://www.curseforge.com/minecraft/mc-mods/ae2-fluid-crafting-rework

### Why would you like the mod added?

This mod makes it a lot easier to do fluid autocrafting by allowing you to use fluids as a crafting ingredient for AE2 processing.
Cryoducts, filled Hardened Frames, alongside the various crafting recipes that need destabilized redstone would be a lot less tedious to do. You can do it right now on AE2 with extra cells but you need to go through it a fairly roundabout and unintuitive way. This rectifies that.

**Comment by King65868** [comment]
Would also require ae2 unofficial extended lite

**Comment by Kanzaji** [comment]
Yea, and AE2 Unofficial Extended was denied already >.>#2045

**Comment by NielsPilgaard** [comment]
This would be a too large change to introduce at this point.
