### ISSUE TITLE
Extra Cells fluid storage cells can't be partitioned.

### ISSUE THREAD

**Issue by Electron248** [EnigmaticaModpacks/Enigmatica2Expert#2077]
### Modpack Version

1.86

### Describe your issue.

All fluid storage cells added by Extra Cells can't be partitioned using a cell workbench from AE2. Fluids may be placed inside the GUI but nothing happens beyond that. There are no issues with other Extra Cells storage cells or AE2 cells.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Electron248#1708

**Comment by NielsPilgaard** [comment]
I'm afraid this is simply a limitation of Extra Cells 2.
