### ISSUE TITLE
New Creative RF Item but no Quest Book Update

### ISSUE THREAD

**Issue by WHOni** [EnigmaticaModpacks/Enigmatica2Expert#2078]
### Modpack Version

1.86

### Describe your issue.

The problem is rather simple. I recently realized that the RFTools Creative Powercell was replaced by the EnderIO Creative Capacitor Bank as the Creative RF Item. With other words: The Creative Powercell recipe is gone, the Creative Capacitor Bank now has the recipe the Powercell had back then (I think it is the same at least) and the Creative Vending Upgrade requires the Capacitor Bank now.
Though I also realized that the Quest Book was not updated. That means you cant complete the Infinite RF Quest, and some of the Quests in the Bragging Rights Questline are dependent on this one -> You cant finish the Bragging Rights Quest Line

### Have you modified the modpack?

Yes

### User Modifications

There are a few custom recipes using voting rewards on the server, I think thats it.

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Jonas#8033

**Comment by Discomanco** [comment]
Quests don't automatically update through updates, and the command `/bq_admin default load` has to be run

**Comment by WHOni** [comment]
I see, thank you that worked. o/
