### ISSUE TITLE
Hard Crash with EmberRoot Zoo Fairy

### ISSUE THREAD

**Issue by Darkere** [EnigmaticaModpacks/Enigmatica2Expert#2079]
### Modpack Version

1.86

### Describe your issue.

Quite a few people (5+) have come to the discord support channel reporting hard crashes when encountering Emberoot Zoo Fairies.

For now the only solution found has been to move the player away and prevent the fairies from spawning by changing the config.

### Crash Report

https://gist.github.com/Darkere/ef17bbe20136df1a8df588c8a97a71b3

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
I'll investigate, thanks 👍

**Comment by joycourier** [comment]
I can second this, still happening to me on 1.86
