### ISSUE TITLE
Replace normal AE2 with AE2 Unofficial Extended Life

### ISSUE THREAD

**Issue by Anthonity** [EnigmaticaModpacks/Enigmatica2Expert#2080]
### URL

https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life

### Why would you like the mod added?

AE2UEL is more performant than normal AE2. The pattern expansion cards would also be really nice addition

**Comment by Kanzaji** [comment]
Duplicate of #2045

**Comment by Anthonity** [comment]
bruh
