### ISSUE TITLE
Unbreakable Electrodes are not craftable

### ISSUE THREAD

**Issue by lekutree** [EnigmaticaModpacks/Enigmatica2Expert#2083]
### Modpack Version

1.86

### Describe your issue.

Cannot put the 100% electrodes into the Induction Smelter.  It will not accept the input 
<img width="265" alt="image" src="https://user-images.githubusercontent.com/116689949/209482586-44ea9257-1f62-4b8d-986e-596a09f81779.png">

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by lekutree** [comment]
Also just noticed I can't put fused quartz into an induction smelter to make hardened glass

**Comment by RaVenInTheDark** [comment]
> Also just noticed I can't put fused quartz into an induction smelter to make hardened glass

long known issue, thermal expansion restricts input. i do recall this working in the past though...

**Comment by Discomanco** [comment]
My original plan was to put it into the AR induction furnace, so I guess it can be moved to that again

**Comment by lekutree** [comment]
Not a bad idea. Would give it a reason to be used

**Comment by NielsPilgaard** [comment]
> My original plan was to put it into the AR induction furnace, so I guess it can be moved to that again

Yes please 😁

**Comment by Discomanco** [comment]
Issue found: The 100% rods were made by combining 2 50% rods - it is meant to only be usable with Engineers Table rods
