### ISSUE TITLE
Infinite Pink Slime using Ice and Fire Dragon Skulls

### ISSUE THREAD

**Issue by RCNOverwatcher** [EnigmaticaModpacks/Enigmatica2Expert#2085]
### Modpack Version

1.86

### Describe your issue.

Due to Ice and Fire treating dragon skulls as entities, it's possible to place dragon skulls down in front of a mob slaughter factory from Industrial Foregoing and get infinite pink slime due to the dragon skull dropping it's own item when it dies.

This is probably not a direct problem with E2E and more of an issue between these two mods but I thought I would report it here just in case!

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

RCN#0001

**Comment by ReiDaTecnologia** [comment]
Make it a feature Niel, do it! XD

**Comment by NielsPilgaard** [comment]
Thanks for the report :)
I'm okay with that interaction, I quite like it tbh 😄
