### ISSUE TITLE
Harvestcraft garden spread clarification

### ISSUE THREAD

**Issue by ghatus0** [EnigmaticaModpacks/Enigmatica2Expert#2088]
### Modpack Version

1.86

### Describe your issue.

The [gardenSpreadRate ](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/blob/e6ff1ba1fb08bedca8aa896129cbf3c50b4702c6/config/harvestcraft.cfg#L170) for Harvestcraft gardens is set to 0, which I assume was meant to prevent any spreading. With the range being 1-100, 0 doesn't prevent the spreading and it is likely defaulting to 30. It seems like [gardenspreadMax](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/blob/e6ff1ba1fb08bedca8aa896129cbf3c50b4702c6/config/harvestcraft.cfg#L172) of 1 prevents any spreading if this is what was intended. The current value of 2 basically limits any garden from spreading if there is already another garden in the chunk, so they can't exactly grow out of control.

The gardens seem to work on normal growth ticks and this opens up some interesting farming options, but I would hate to invest too heavily in it if they aren't meant to spread at all. 

This can be quickly tested by placing a garden in a chunk and using a supremium watering can on it for 10-60s.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

ghatus#4338

**Comment by NielsPilgaard** [comment]
I'll change to 1 then, ty 👍

**Comment by NielsPilgaard** [comment]
We usually don't close issues until they've been released :)
