### ISSUE TITLE
Forestry Saplings unusable in DNA extractor

### ISSUE THREAD

**Issue by chadwood1999** [EnigmaticaModpacks/Enigmatica2Expert#2092]
### Modpack Version

1.86

### Describe your issue.

Looks like the recipe for saplings in DNA extractor got removed in commit [da7ebd9dce8ce181ef000f64b9e6c68cc6df4a69](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/commit/da7ebd9dce8ce181ef000f64b9e6c68cc6df4a69). Was this intentional? 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
I believe it was intentional, but in hindsight I'd rather have Forestry saplings working 😄

**Comment by Anthonity** [comment]
you can plant forestry trees to get butterflies and make a powered spawner for them
