### ISSUE TITLE
Replace AE2 through AE2 Unofficial Extended Life

### ISSUE THREAD

**Issue by Irgendwer01** [EnigmaticaModpacks/Enigmatica2Expert#2093]
### URL

https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life

### Why would you like the mod added?

AE2 Unofficial Extended Life is an fork of AE2 that is actively maintained containing many bug fixes, performance improvements and some new Content like the Pattern Expansion card which allows to expand the slots an Interface has. It is completely compatible with already existing AE2-Setups and allows for issueless switch.

**Comment by ShykhovMyron** [comment]
Why is it not planned?
This will fix a lot of things and improve perfomanse af

**Comment by heathercomputer** [comment]
> Why is it not planned? This will fix a lot of things and improve perfomanse af

They tried. It broke compatability with recipes involving items from a lot of mods, caused crashloops if any crafts were in progress, and did not have any tangible benefits.

**Comment by ShykhovMyron** [comment]
Thanks for answering 
Yep iv tried to switch and now i cant craft infinity ingot 

And it's difficult to downgrade to ae2 as i have Expansion cards everywhere in ME interfaces

**Comment by HeatherComputer** [comment]
In general, I'd say expansion cards just encourage bad behaviour anyway lol
