### ISSUE TITLE
Secondary recipe for Forestry wax capsule not working

### ISSUE THREAD

**Issue by ghatus0** [EnigmaticaModpacks/Enigmatica2Expert#2096]
### Modpack Version

1.86

### Describe your issue.

There is a recipe to make wax capsules using Harvestcraft pressed wax instead of Forestry beeswax but it doesnt seem to work.

![2023-02-03_17 17 45](https://user-images.githubusercontent.com/6835699/216742052-5376bc6d-295b-401e-b1ba-383cd8100124.png)
![2023-02-03_17 17 58](https://user-images.githubusercontent.com/6835699/216742059-2e0a4c31-3cbf-44e9-9efe-83de8fca1088.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

ghatus#4338

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.
