### ISSUE TITLE
Crash when rendering emberroot fairy

### ISSUE THREAD

**Issue by jurrejelle** [EnigmaticaModpacks/Enigmatica2Expert#2098]
### Modpack Version

Enigmatica 2 Expert 1.86 (1.12.2)

### Describe your issue.

When exploring the world, sometimes my game randomly crashes. Looking at the stacktrace, it seems to be an issue with the rendering of the Fairy entity model from the EmberRoots modpack. I've attached my crash log.

### Crash Report

https://gist.github.com/jurrejelle/76115c78eaffa5946a4e9b3a88d27160

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

jurrejelle#4936

**Comment by Kanzaji** [comment]
Duplicate of #2079

**Comment by jurrejelle** [comment]
Thank you, closed
