### ISSUE TITLE
Game Crashing after Opening World

### ISSUE THREAD

**Issue by Crdoes** [EnigmaticaModpacks/Enigmatica2Expert#2102]
### Modpack Version

1.86

### Describe your issue.

Every time i go onto a server the game crashes instantly or after a few minutes
Tried repairing the installation and updating java
[hs_err_pid4452 2..log](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/files/10768984/hs_err_pid4452.2.log)

### Crash Report

https://gist.github.com/Crdoes/dc40a869e67d349cc3d51bbc3abb985f

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Crodes#6115

**Comment by NielsPilgaard** [comment]
You seem to be using the version of Java that is shipped with CurseForge, which is very old unfortunately. Head over to our Discord if you need help updating your CurseForge app to use your latest Java 8.
