### ISSUE TITLE
Minecraft crashes before local server loaded

### ISSUE THREAD

**Issue by Actticus** [EnigmaticaModpacks/Enigmatica2Expert#2103]
### Modpack Version

1.86

### Describe your issue.

Minecraft crashes before server loaded with code -1

### Crash Report

No crash log in directory

### Latest Log

https://gist.github.com/Actticus/ffdecc5d8887b062ce498231cc74fe03

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

nullInside |Tim|#8748

**Comment by NielsPilgaard** [comment]
Seems like the `advRocketry/planetDefs.xml` file in your save has corrupted, deleting it ought to resolve this :)
