### ISSUE TITLE
No Longer Possible to Use Ex Nihilo Hammers to Create Wood Chippings

### ISSUE THREAD

**Issue by JesusFreakTW** [EnigmaticaModpacks/Enigmatica2Expert#2104]
### Modpack Version

1.86

### Describe your issue.

Wood chippings are no longer obtainable from logs using Ex Nihilo hammers. This makes early game cardboard box crafting difficult. I tried sledge hammers from Tinker's and standard hammers from Ex Nihilo and Ex Compressum. It seems to be an issue with the Ex Compressum mod. The Ex Compressum config still has the wood chipping from logs recipe set to true, and I can't find any other reason the recipe wouldn't work. The wood chipping recipe doesn't show up in JEI. I thought the issue may be a result of this commit:   [b98a11fa6c7aad6f481313b41c7222e2e7b79ec2](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/commit/b98a11fa6c7aad6f481313b41c7222e2e7b79ec2). However, I went and checked version 1.83, the version before this commit was made, and the player is still not able to create sawdust using ex nihilo hammers. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

JesusFreakTW#3327

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by NielsPilgaard** [comment]
Ah that makes sense. Let's keep it disabled then.
