### ISSUE TITLE
Load Crash

### ISSUE THREAD

**Issue by TatsuyaBR** [EnigmaticaModpacks/Enigmatica2Expert#2106]
### Modpack Version

1.86

### Describe your issue.

Crashes when start load, aparently gendustry

### Crash Report

<script src="https://gist.github.com/TatsuyaBR/6a2d8fd2b29506c87e1bd081567df796.js"></script>

### Latest Log

<script src="https://gist.github.com/TatsuyaBR/bd266c72588a85fdacd3a375aea8b644.js"></script>

### Have you modified the modpack?

Yes

### User Modifications

Crafting tweaks

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by TatsuyaBR** [comment]
Now its working, i dont know how.

**Comment by tuca1234567890** [comment]
sometimes it just crashes randomly on startup, it's normal
