### ISSUE TITLE
IC2 overlapping oredict entries: wrong type of cable accepted

### ISSUE THREAD

**Issue by The--Captain** [EnigmaticaModpacks/Enigmatica2Expert#2110]
### Modpack Version

2.8.221-ex112

### Describe your issue.

The author is well aware of this exact bug, and it is BS that they keep closing this issue
![stillnotfixed](https://user-images.githubusercontent.com/4986916/223349450-1ff41cee-19a0-44e3-96f3-55e3b4268871.jpg)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by Discomanco** [comment]
You have the wrong modpack there mate.
You're in ATM3, this is E2E, and this is not an issue in our pack
![image](https://user-images.githubusercontent.com/4707702/223389932-10a65fb6-8b34-40dc-80c6-dc370ea34c24.png)

**Comment by Buuz135** [comment]
If you wrote that message in the image you are an asshole and you don't deserve to be playing any pack

**Comment by Kanzaji** [comment]
What even happened here 👀

**Comment by The--Captain** [comment]
Bloody hell. A thousand apologies.  Not sure how this wound up here.
