### ISSUE TITLE
List of various small fixes/adjustments

### ISSUE THREAD

**Issue by MorganSimic** [EnigmaticaModpacks/Enigmatica2Expert#2114]
### Describe your suggestion

Here is a list of small things i noticed over time. I will order them by ease of fixing, easiest being on top.

1. RFTools Screen Controller Recipe should not require a RFTools casing. I suggest an XU2 casing or similar.
2. RFTools Elevator should not require an RFTools casing. Suggestion: OpenBlocks Elevator block, XU2 casing or similar.
3. Draconic Evolution Flux and Fluid Gate should not require a Draconic Core. Suggestion: NC casing.
4. Redstone Ore is meltable in TComplement Melter, possibly shortcutting intended signalum progression. Suggestion: Simply remove redstone ore melting to bring it in line with other means of obtaining destabilized redstone.
5. Nether Ores do not have correct mining level. Copper at most, often even none. Iirc they were at cobalt or manuyllyn tier. As it now it allows shortcutting mining levels in an obvious way. And it feels weird.
6. I noticed that EIO copper and tin powder showed up in JEI as an output from ID squeezer. Actual output is correctly unified, probably UniDict or something acting up.
7. Remove LibVulpes Iron and Steel rods from oredict, so they don't show up in JEI cylcing and make crafting stuff that requires those in the storage scanner easier.
8. Debatable: Add IF Biofuel as valid compression dynamo fuel. Would feel in line with the rest but would enable really efficient power generation in conjunction with Immersive Tech steam turbine and boiler augment. It's mostly fine, as it also requires a fast and diverse crop farm. One bioreactor can then run multiple steam turbines at 96k rf/t, when the fuel value is set comparable to crystallized canola. IF Biofuel is currently only usable in IF generators and EIO combustion generator and Advanced Generators.

### Why would you like this added/changed?

Those would make the pack feel even more smooth. How is that even possible?

**Comment by NielsPilgaard** [comment]
I agree with all 8 suggestions, good stuff Morgan!

... PRs are very welcome, hint hint... 😄
