### ISSUE TITLE
Unable to craft any Elite tier Induction Cells or Providers

### ISSUE THREAD

**Issue by The-Night-Fox** [EnigmaticaModpacks/Enigmatica2Expert#2118]
### Modpack Version

1.86

### Describe your issue.

I discovered when trying to auto craft some Ultimate Providers that the recipe must be broken for the Elite tier Cells or Providers that it did't matter if the Advanced Energy Cube was owned by me or if was unowned straight out of the ae2 auto crafting. I read online that sometimes if the Cube's are owned or not can mess up the recipe.

### Have you modified the modpack?

Yes

### User Modifications

Added ChickenChunks-1.12.2-2.4.2.74-universal

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Spyfox180#5055

**Comment by NielsPilgaard** [comment]
Thanks for the report.

I'm thinking you may need to insert an auto-crafted Advanced Energy Cube into the pattern for it to work. 
Could you try that please? :)

**Comment by The-Night-Fox** [comment]
I have the complete recipe I even tried today to craft the elite tiers in a normal crafting table by hand and was unable to come up with a combination to get the recipe to work. I can provide a video via YouTube if requested.

**Comment by The-Night-Fox** [comment]
So it seems to have fixed itself I'm not sure what happened I have restarted my server and my install and couldn't get it to work and I went to make a video to show you guys and it seems ti be working now for some reason. I appreciate the time and effort you guys put into this pack it really shows. I do apologize for the bug not bug.
