### ISSUE TITLE
Alumite uses Aluminium instead of Aluminum

### ISSUE THREAD

**Issue by MukizuL** [EnigmaticaModpacks/Enigmatica2Expert#2122]
### Modpack Version

1.90

### Describe your issue.

In advanced metallurgic fabricator alumite recipe uses Aluminium(JAOPCA) but it should use Aluminum(TiC.)
1.90 Changelog:
"Updated scripts to use Aluminum instead of Aluminium, un-breaking a few recipes".

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Fpj_cool#7079

**Comment by MukizuL** [comment]
1.90 from releases

**Comment by Discomanco** [comment]
We have released serveral hotfixes since, so I'll recommend updating and see if its still an issue

**Comment by Discomanco** [comment]
Appears to be fine in 1.90c
![image](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/4707702/9c91ca02-1595-47a9-97c1-be0435f47ecf)
