### ISSUE TITLE
Encoded pattern for Stellar Alloy block is broken

### ISSUE THREAD

**Issue by MukizuL** [EnigmaticaModpacks/Enigmatica2Expert#2123]
### Modpack Version

1.90c(incompatibility with 1.86 save?)

### Describe your issue.

![image](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/53896777/b7235b33-ddad-4448-a4db-171294027df4)
This encoding results in AE2 using this one
![image](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/53896777/dec648cd-b046-40d4-980b-ec4108cfbad1)
![image](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/53896777/b1913201-827e-4399-99da-da09dade8900)
The craft, if crafting manually, works.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Fpj_cool#7079

**Comment by Discomanco** [comment]
Cannot replicate. Please retry your experiment in 1.90c
![image](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/4707702/aaae6d19-89e0-46e6-a558-461d727d4758)
![image](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/4707702/fc51137f-b518-45a8-a1a3-84dff632f365)
![image](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/4707702/c89b4be4-eace-419e-b4c1-d4efd0b2ca74)

**Comment by MukizuL** [comment]
Craft works in new world. Does it mean that update somewhat incompatible with worlds on 1.86?

**Comment by Discomanco** [comment]
Have not tested that, but it *should* work. Will test further

**Comment by MukizuL** [comment]
The pattern itself is encoded correctly. This issue is when you try to autocraft.

**Comment by MukizuL** [comment]
Found the problem. After converting world encoded pattern "Ludicrite block->ludicrite ingots" automatically converts to "Ludicrite block->Stellar Alloy block", so it's not a bug but a thing you should check after converting the world.
