### ISSUE TITLE
No recipe for aluminum brass. TC Smeltery not accepting fuels besides lava

### ISSUE THREAD

**Issue by Metosys** [EnigmaticaModpacks/Enigmatica2Expert#2124]
### Modpack Version

1.90c

### Describe your issue.

There is no way to craft aluminum brass.

I've only tested liquid starlight and blazing pyrotheum in the smeltery, both give 'invalid fuel'.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thanks for the report, both issues are fixed in-dev :)
