### ISSUE TITLE
Pam's Harvestcraft water duping

### ISSUE THREAD

**Issue by BHGull** [EnigmaticaModpacks/Enigmatica2Expert#2127]
### Modpack Version

1.90e

### Describe your issue.

Pam's harvestcraft has a intended crafting recipe to make 8 fresh water out of 1 water bucket. For some reason, the fresh water also counts as a water bucket, letting you dupe fresh water.

### Have you modified the modpack?

Yes

### User Modifications

Added WorldEdit

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

BlackHeadedGull#6596

**Comment by NielsPilgaard** [comment]
Thank you for the report, but this is intended 😊
