### ISSUE TITLE
Wiki, Tips section: #45 has typo

### ISSUE THREAD

**Issue by HaxtonSale1** [EnigmaticaModpacks/Enigmatica2Expert#2133]
### Modpack Version

(N/A)

### Describe your issue.

`45. Go into the Twilight Forest early, or prepare strong Weapons and Armor. It's surface is safe, but points of interest have a lot of enemies.`

shouldn't it be

`45. Go into the Twilight Forest early, **and** prepare strong Weapons and Armor. It's surface is safe, but points of interest have a lot of enemies.`

?

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Haxton1

**Comment by NielsPilgaard** [comment]
Fixed thank you 👍
