### ISSUE TITLE
Modular machine to automate the Actually Additions Atomic Reconstructor

### ISSUE THREAD

**Issue by juanitierno** [EnigmaticaModpacks/Enigmatica2Expert#2136]
### Describe your suggestion

I believe it would be nice to have a Modular Machines version of the AA reconstructor for cleaner automation later on in the pack.

### Why would you like this added/changed?

Normally I build a setup with the reconstructor + magnet blocker + item collector with whitelist + entity detector to not fire the laser constantly.

I think it would be nice to have a modular machine able to automate the same thing in a cleaner manner. Similar to how the crystal growth accelerator automates the "drop in a pool of water" crafting mechanic of AE2.

**Comment by NielsPilgaard** [comment]
I don't think there's any need for this to be honest.
