### ISSUE TITLE
(Unsolvable?) Problem: TE Steam Turbine consumption rate limited by internal buffer

### ISSUE THREAD

**Issue by HaxtonSale1** [EnigmaticaModpacks/Enigmatica2Expert#2140]
### Modpack Version

1.90f

### Describe your issue.

Pumping in 8000mB/t of steam into this steam dynamo, which should be able to produce 6720RF/t: 
![2023-07-26_10 32 31](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/13237198/da8cc96a-5dc6-4260-bbf8-f985250cf287)

But instead, it only produces 240RF/t
![2023-07-26_10 32 42](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/13237198/d1a17208-1d79-445f-924d-ccaf69485271)

Remove all Aux. Transmission Coils so the consumption rate falls below 2000mB/t (half of the internal buffer) and it produces as expected
![2023-07-26_10 36 25](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/13237198/9c400684-a5cd-4407-bfab-084b9ce09774)
![2023-07-26_10 36 29](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/13237198/1df31fc6-ee22-436d-8a3e-52b96201550d)

I don't see anything on the config file that can affect buffer size. 

### Crash Report

None

### Latest Log

None

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Haxton1

**Comment by NielsPilgaard** [comment]
Iirc we've investigated this issue before, and came up short :/ we can't fix it

**Comment by HaxtonSale1** [comment]
Well that's a bummer. 
ig contacting Thermal is also out of question bc it is 1.12

**Comment by NielsPilgaard** [comment]
Yeah :/ turning down the config is most likely our only option,and that wouldn't help much..

**Comment by HaxtonSale1** [comment]
understandable, ig I'll close this

**Comment by Anthonity** [comment]
bansoukou?
