### ISSUE TITLE
EnderIO Melodic and Stellar alloys depend on depreciated Extreme Reactors items.

### ISSUE THREAD

**Issue by Jaffiss** [EnigmaticaModpacks/Enigmatica2Expert#2141]
### Modpack Version

1.90f

### Describe your issue.

EnderIO's Melodic and Stellar alloys depend on depreciated Extreme Reactors items that have been disabled in the latest (1.90f) version making them uncraftable and obtainable only through loot mechanics.

This breaks the entire modpack as both are needed for progression items such as Draconic Cores, Wyvern Cores, and Ultimate Ingots.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by HaxtonSale1** [comment]
While the individual ingots are not craftable, the blocks are.

**Comment by NielsPilgaard** [comment]
We'll remove Extreme Reactors and add tooltips explaining how to obtain these items in the next update :)

**Comment by Jaffiss** [comment]
> While the individual ingots are not directly craftable, the blocks are.

The blocks also depend on Extreme Reactors items to craft, which, again, are depreciated.

**Comment by NielsPilgaard** [comment]
The recipes for them won't change though, the blocks are craftable through the Carpenter :)
