### ISSUE TITLE
game zooms in over time

### ISSUE THREAD

**Issue by DreamMojo** [EnigmaticaModpacks/Enigmatica2Expert#2152]
### Modpack Version

1.90g

### Describe your issue.

![2023-09-10_10 01 31](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/129336275/22aba3af-d247-4ddc-b1ba-369c2e163733)
![2023-09-10_10 02 25](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/129336275/94753016-03fc-4309-b9ee-6b81ac513c0b)
both photos are on quake pro fov. 
i know the issue is not my fov because the item in my hand moves off the screen, which does not happen when changing fov.
the issue resets after a client restart but then comes back. this happens on all worlds.

### Latest Log

https://gist.github.com/DreamMojo/6c8bdcc573780d230460f17bddb722cf

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

FreamMojo

**Comment by DreamMojo** [comment]
UPDATE: restarting my computer seems to have fixed the issue

**Comment by DreamMojo** [comment]
aaand the issue is back

**Comment by ReiDaTecnologia** [comment]
This is the weirdest specific setup bug i ever seem

**Comment by NielsPilgaard** [comment]
Please try reinstalling, I hope this is some weird setting 😅

**Comment by DreamMojo** [comment]
i just updated my gpu driver. if that doesnt work ill try running the game in linux and transfer my save over there

**Comment by DreamMojo** [comment]
> Please try reinstalling, I hope this is some weird setting 😅

would just deleting all of the mod configs do essentially the same things? would i lose any of my save data if i reinstall?

**Comment by NielsPilgaard** [comment]
It would not do the same thing - You would need to backup your world folder, and move it into the new install, then you won't lose data :)

**Comment by DreamMojo** [comment]
i updated my display driver and it hasnt happened yet, hope it doesn't come back!

**Comment by DreamMojo** [comment]
I FIXED IT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! it was my mouse buttons that were sooming in and out for some reason. the same button that i use as item hotkeys
