### ISSUE TITLE
Invalid Dimension Builder Recipe

### ISSUE THREAD

**Issue by KyleXB** [EnigmaticaModpacks/Enigmatica2Expert#2154]
### Modpack Version

1.90g

### Describe your issue.

When trying to craft the dimension builder (RFTools), all the items are placed in the correct position and order:
![image](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/72575943/f5e39c38-0120-434a-a223-bd95ce66543f)
Celestial Crystal is maxxed out just like in the JEI recipe:
![image](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/72575943/5fe3b589-ec52-4b26-af80-b67b104d56c7)
And the Digital Miner doesn't have any attachments:
![image](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/72575943/84760999-bc5a-4c1d-a567-bd192495f11c)

I tried to also use JEI to place the items into the AE2 crafting terminal area, and it failed to place the attuned crystal, the advanced miner, and the digital miner, so the problem likely lies with one of those three: 
![image](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/72575943/9d8f497f-d39c-4f65-852a-d3ea72aa2ccb)

Then also tried making it into a pattern, in which the crafting terminal found every item valid except for the attuned crystal:
![image](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/72575943/133022f9-edb4-468c-b9be-dd4ddb92461c)

Also tried crafting it on a normal crafting table and a Botania assembly halo.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

zypherial#0000

**Comment by Discomanco** [comment]
Wrong attunement on crystal
