### ISSUE TITLE
The Fast Workbench mod breaks when setting up a multiplayer server

### ISSUE THREAD

**Issue by miosar** [EnigmaticaModpacks/Enigmatica2Expert#2156]
### Modpack Version

1.90g

### Describe your issue.

When I host the server , I get both fatal registry entries and an error saying that Recipe minecraft:crafting_table (net.minecraft.item.crafting.ShapedRecipes@4a7427f9) produces unregistered item minecraft:crafting_table (net.minecraft.item.ItemBlock@dddcd91) at com.google.common.util.concurrent.Futures.wrapAndThrowUnchecked(Futures.java:1329) ~[guava-21.0.jar:?]

### Latest Log

<script src="https://gist.github.com/miosar/a519d7a784d72b474e42049f3492ae92.js"></script>

### Have you modified the modpack?

No

### User Modifications

After the recipe and the fatal registry issues I deleted the Fast Workbench mod. It removed the recipe issue but the registry issue stayed.

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

miosar

**Comment by MommyHeather** [comment]
This is caused by a broken vanilla installation, and isn't really related to FastWorkbench.

Serverside, you can try reinstalling the server.
Clientside, Curseforge has a button to repair the vanilla installation, or other launchers you should just reinstall the pack.
