### ISSUE TITLE
EnderIO Conduits Config Change

### ISSUE THREAD

**Issue by pollymonosumo93** [EnigmaticaModpacks/Enigmatica2Expert#2160]
### Describe your suggestion

There is a setting in EnderIO config which controls connection of higher and lower tier of power cable could it be changed to true from false

### Why would you like this added/changed?

There is annoying thing when having EnderIO power cables as the method to deliver power through out the base and that is when you want to upgrade the power cables to a higher tier person needs to craft more then there is of lower cables so that machines get power and while doing that two annoying things can happen person calculated wrong and did not have enough so machine is with out power and two even though person craft enough there can always be one power cable left in the line is lower tier and won't connect to the higher tier and person needs to deep search their base to find where the cable is which is annoying but if the config would change that thing won't happen because person only need to upgrade the cable connected to the batter and to the machine all other in the line could be a lower powercable

**Comment by NielsPilgaard** [comment]
To be honest I don't want to allow using mostly lower tier cable and getting higher tier throughput, seems hacky to me.

**Comment by Discomanco** [comment]
Honestly, it would make higher tier cables useless outside of just the connections.
Miscounted? Well, don't miscount, or, move the machine closer temporarily to fix your miscount

**Comment by MommyHeather** [comment]
> > To be honest I don't want to allow using mostly lower tier cable and getting higher tier throughput, seems hacky to me.
> 
> why won't you allow using mostly lower tier cables?

The way I see it - you stick one stellar conduit by your production and use the minimum tier everywhere else, maybe a small upgrade for the hungrier things, and suddenly that's effectively a massive stellar conduit line for the cost of... one stellar conduit. That to me is overpowered and doesn't belong in an expert pack.

**Comment by NielsPilgaard** [comment]
> > To be honest I don't want to allow using mostly lower tier cable and getting higher tier throughput, seems hacky to me.
> 
> @NielsPilgaard why won't you allow using mostly lower tier cables?

It makes them far cheaper overall, and I don't want that. This is an expert pack, they are intentionally expensive.
