### ISSUE TITLE
The enigmatica 2 expert extended mod pack is not loading

### ISSUE THREAD

**Issue by DegraNemo** [EnigmaticaModpacks/Enigmatica2Expert#2169]
### Modpack Version

1.29.1

### Describe your issue.

The mod pack does not start. at the first launch, everything was fine, but before the start, a window opened with the installation of optifine additionally.
I have installed it. then everything loaded and I went into the game, went into the settings and set up everything I needed there at once, after that everything hung up. I tried restarting and a window opened at startup with a link to crash.
what to do, please help.

### Crash Report

https://gist.github.com/DegraNemo/0606fd221aed84b208b059574faa2b48#file-crash-2024-02-01_19-28-23-client-txt

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MommyHeather** [comment]
E2E-Extended is not supported here.

You'll be better off reporting this [on their github](https://github.com/Krutoy242/Enigmatica2Expert-Extended/issues) or their [discord](https://discord.gg/P2MTyxHZtw).

**Comment by DegraNemo** [comment]
thanx
