### ISSUE TITLE
Flying is not enabled on this server

### ISSUE THREAD

**Issue by Solizaam** [EnigmaticaModpacks/Enigmatica2Expert#2170]
### Modpack Version

1.90g   Server: 1.9g

### Describe your issue.

We were trying to launch the rocket from advanced rocketry mod. But we were kicked for “Flying too long” and the server indicated that flying is not enabled on this server. But we’ve checked the server.properties file. It shows  “allow_flight=true. So we actually don’t know how to solve this issue. We are appreciative if solutions are provided. Millions of thanks!

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Solizaam** [comment]
OHHH! It works! Thank you very much!

**Comment by MommyHeather** [comment]
No problem! You should probably close this issue now that it's resolved hehe
