### ISSUE TITLE
Draconic Gate Can't Be Unlocked

### ISSUE THREAD

**Issue by MasterNoob32** [EnigmaticaModpacks/Enigmatica2Expert#2171]
### Modpack Version

1.90g

### Describe your issue.

https://imgur.com/a/Jqd9IZl

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
In order to update your questbook, you need to run the following commands:

/bq_admin default load 
/bqs_loot default load
