### ISSUE TITLE
Extreme reactor core cannot be produced

### ISSUE THREAD

**Issue by suze3** [EnigmaticaModpacks/Enigmatica2Expert#2175]
### Modpack Version

1.86

### Describe your issue.

The following information is prompted during the production of the Extreme Reactor Core：Mod set for removal, all recipes and
functionalities disabled. Update all your autocrafting and systems to no longer use this mod.
![b23f17c2a37b22137d663da07a5138d](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/162103890/5a5830a1-f922-473f-8536-bb78216a4e0c)
My English is not very good, please forgive me
I want to know how to solve this problem
thanks

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Discomanco** [comment]
Your instance has been updated to version 1.90g.
You can run the command `/bq_admin default load` to have the quests reflect this change.
