### ISSUE TITLE
Advanced Carpenter Cryotheum keeps turning to water

### ISSUE THREAD

**Issue by Breedon85** [EnigmaticaModpacks/Enigmatica2Expert#2186]
### Modpack Version

1.90f

### Describe your issue.

I know I'm not on the latest version but I'm so far along I'm afraid of something breaking if I update lol.

Every once and a while my advanced carpenter will break because the Gelid cryo turns to flowing water?
Is it normal for it to "warm up" and turn to water?

### Have you modified the modpack?

Yes

### User Modifications

Changed power consumption of wireless AE2
Changed swing timer back to old combat "Classic Combat"
Always able to eat mod

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Breedon85** [comment]
Ok I think I figured it out. I have a set up that involves Universal Fluid Cells and a Mechanical User. Every pattern includes a fluid cell with the exact fluid it needs for the operation.  If I request a LOT of something that needs water for example it will use the cells on the fluid input hatch. If the hatch becomes full the user will keep trying to place water in via the cells but can't because its full so for some reason it places the water on the other side of the Hatch destroying the Gelid Cryo that was behind it and turning it all into water.

Fixed it by moving the User to the other side where a solid block is behind the Hatch instead of the cryo.

Sorry to bother lol

**Comment by MommyHeather** [comment]
Surely a better option would be a pipe, rather than a mechanical user setup? I didn't even know you *could* click on a hatch like that honestly

**Comment by Breedon85** [comment]
> Surely a better option would be a pipe, rather than a mechanical user setup? I didn't even know you _could_ click on a hatch like that honestly

I didn't want to make a bunch of Advanced Carpenters because at the time I didn't have a lot. Also you need different amounts and types of fluid for each recipe.  ME Interface to a Chest, Materials and the exact amount of Redstone, water, Primal mana..etc(fluid in the Cells) Filter materials out one side to Input hatch and fluid cells to user that "Uses" cells on the Fluid input hatch. exact fluid needed inputted then filter back out the empty cells back to AEsystem.  only other thing is to have a fluid transposer set up for each different fluid to fill up the cells on demand. think it's 5.

**Comment by MommyHeather** [comment]
I have two advanced carpenters, I include buckets or other containers in my patterns and just empty them into a tank - I use lasers to filter the destination, and then simply use a fluid pipe to move from the tank into the fluid hatch. No users involved, and multiple fluids (two carpenters just for the sake of speed)
