### ISSUE TITLE
AE2 Inscriber is making my game lag?

### ISSUE THREAD

**Issue by m-sweitzer** [EnigmaticaModpacks/Enigmatica2Expert#2189]
### Modpack Version

1.12.2

### Describe your issue.

SO I have my inscribers set up to auto craft, but every time I auto craft a recipe that uses the inscribers in some way it causes my game to lag.  Like it feels like I am playing on 500 ping in a solo world lol.  And nothing seems to fix it except for leaving and rejoining which is really annoying to have to do every time I auto craft something using the inscriber.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Chip092

**Comment by ReiDaTecnologia** [comment]
Use Spark (it already comes with the pack) to profile (/spark profiler) then send the link here

**Comment by m-sweitzer** [comment]
https://spark.lucko.me/5dmlqJgROI

**Comment by MommyHeather** [comment]
![image](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/66441550/e23a4ebc-5061-4eca-b469-9980be0b6e9a)
Jesus christ.

**Comment by MommyHeather** [comment]
Ditch the logistical transporters. Your pc will thank you.

**Comment by ReiDaTecnologia** [comment]
^ yep

**Comment by m-sweitzer** [comment]
got it thanks
