### ISSUE TITLE
Aluminum ore generation in config uses metadata for Iridium insteaad

### ISSUE THREAD

**Issue by cppietime** [EnigmaticaModpacks/Enigmatica2Expert#2191]
### Modpack Version

1.90h

### Describe your issue.

`/config/cofh/world/01_thermalfoundation_ores.json` has a section for aluminum ore generation. It uses a metadata value of 7, which corresponds to iridium ore, instead of 4, which corresponds to aluminum. I'm _fairly_ confident I have not accidentally changed this myself.

### Have you modified the modpack?

Yes

### User Modifications

Modified food and crop config values. If I accidentally changed this metadata without realizing, and someone else can confirm that the default value is 4, close the issue.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MommyHeather** [comment]
![image](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/assets/66441550/62808ff8-79fe-4265-924b-df3307106ad2)
Default is four. Unmodified e2e-1.90h client install.

**Comment by MommyHeather** [comment]
I can't personally close this issue, but you should be able to @cppietime

**Comment by MommyHeather** [comment]
https://github.com/EnigmaticaModpacks/Enigmatica2Expert/blob/master/config/cofh/world/01_thermalfoundation_ores.json#L52

and just for good measure, figured I'd check the config on github
