### ISSUE TITLE
quest book refuses to work altogether

### ISSUE THREAD

**Issue by seddou9** [EnigmaticaModpacks/Enigmatica2Expert#2194]
### Modpack Version

1.90h

### Describe your issue.

quest book does nothing at all and stopped working all of the sudden,for context,i switched from tlauncher to multiMC due to safety and privacy concerns and moved my enigmatica 2 expert file to the new launcher,ever since then the quest book stopped working completely
video example:https://youtu.be/LAjdOIQqAkk

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MommyHeather** [comment]
This is a result of piracy.

**Comment by seddou9** [comment]
> This is a result of piracy.
i downloaded the modpack from the official curseforge website,so no,its not piracy

**Comment by MommyHeather** [comment]
You.. literally used tlauncher.

Yes, it is a result of piracy.
Downloading a pack from the curseforge website and pirating the game are not mutually exclusive concepts, and funnily enough pirates tend to download from the website more often than legitimate players.

**Comment by seddou9** [comment]
> You.. literally used tlauncher.
> 
> Yes, it is a result of piracy. Downloading a pack from the curseforge website and pirating the game are not mutually exclusive concepts, and funnily enough pirates tend to download from the website more often than legitimate players.

but piracy isnt the problem at play here,i played multiple modpacks that had betterquesting and never encountered this issue,rather than this problem the modpack runs great and no other mod has had an issue

**Comment by MommyHeather** [comment]
Piracy *is* the problem at play here. It's also illegal and unsupported.

**Comment by NielsPilgaard** [comment]
We do not support piracy, nor do we condone the "hidden" racism in your bug report's video.
