### ISSUE TITLE
exit code 255

### ISSUE THREAD

**Issue by brotherman123** [EnigmaticaModpacks/Enigmatica2Expert#2196]
### Modpack Version

i think 14.23.5.2860 or curseforge

### Describe your issue.

there is a bug which only works on specific worlds its the exit code 255 bug. I have only gotten this twice first time i had to restart but now as i am too far i get it. As soon as it loads terrain it freezes and without saying not responding crashes with the minecraft launcher saying exit code 255 no other context maybe this file would help though.

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  EngineersDoorsLoadingPlugin (engineers_doors-1.12.2-0.9.1.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  Controllable (controllable-0.11.1-1.12.2.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.2.0.4.jar)
  UniDictCoreMod (UniDict-1.12.2-3.0.10.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  ToolProgressionPlugin (toolprogression-core-1.12.2-1.6.12.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-2.0.0-13.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
  RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  GiveMeBackMyHpCore (give-me-back-my-hp-1.12.2-1.0.0.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.78-core.jar)
  Plugin (NotEnoughIDs-1.5.4.4.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  serializationisbad (serializationisbad-1.5.2.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.8.3+274990f.jar)
  PluginLoader (MemoryTester-0.4.2.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 7/27/24 9:22 PM
Description: FML will not run in demo mode

java.lang.RuntimeException
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:225)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 6.7.6-200.fc39.x86_64
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 714608416 bytes (681 MB) / 1072693248 bytes (1023 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
EngineersDoorsLoadingPlugin (engineers_doors-1.12.2-0.9.1.jar)
  nihiltres.engineersdoors.common.asm.EngineersDoorsClassTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
  
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
Controllable (controllable-0.11.1-1.12.2.jar)
  
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
ColytraLoadingPlugin (colytra-1.12.2-1.2.0.4.jar)
  c4.colytra.asm.ElytraTransformer
UniDictCoreMod (UniDict-1.12.2-3.0.10.jar)
  wanion.unidict.core.UniDictCoreModTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
ToolProgressionPlugin (toolprogression-core-1.12.2-1.6.12.jar)
  tyra314.toolprogression.core.asm.ToolProgressionClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-2.0.0-13.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
  lumien.randomthings.asm.ClassTransformer
RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
  com.therandomlabs.randompatches.core.RPTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
GiveMeBackMyHpCore (give-me-back-my-hp-1.12.2-1.0.0.jar)
  xyz.phanta.givemebackmyhp.GiveMeBackMyHpClassTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.78-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
Plugin (NotEnoughIDs-1.5.4.4.jar)
  ru.fewizz.neid.asm.Transformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  
serializationisbad (serializationisbad-1.5.2.jar)
  io.dogboy.serializationisbad.legacyforge.SIBTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.8.3+274990f.jar)
  li.cil.oc.common.asm.ClassTransformer
PluginLoader (MemoryTester-0.4.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 545.29.06' Renderer: 'Quadro M1000M/PCIe/SSE2'`

### Have you modified the modpack?

Yes

### User Modifications

i added the controllable mod

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MommyHeather** [comment]
`i think 14.23.5.2860 or curseforge`
Neither of these are valid pack versions.

What launcher are you using exactly?

**Comment by brotherman123** [comment]
thats the curseforge version i mistook for the e2e version. I think the version is 1.90 (and i use curseforge)

**Comment by NielsPilgaard** [comment]
Looking at the crash report, it appears that you do not have a valid minecraft account.

**Comment by MommyHeather** [comment]
That's what I was thinking, honestly..

**Comment by brotherman123** [comment]
i do i have a un pirated regular pack

**Comment by NielsPilgaard** [comment]
In that case I recommend you log out and in again, and try again.

**Comment by brotherman123** [comment]
the game crashed same exit code

**Comment by NielsPilgaard** [comment]
Looks like there are several issues: 
- The spark mod appears to be corrupt. A reinstall ought to help.
- Your advanced rocketry `planetDefs.xml` is corrupt, go into your world folder under `advRocketry` and delete the `planetDefs.xml` while you're not in the game.

**Comment by brotherman123** [comment]
> Looks like there are several issues:
> 
>     * The spark mod appears to be corrupt. A reinstall ought to help.
> 
>     * Your advanced rocketry `planetDefs.xml` is corrupt, go into your world folder under `advRocketry` and delete the `planetDefs.xml` while you're not in the game.

what version of spark does 1.90h use? i need a copy as no version is specified in the files

**Comment by brotherman123** [comment]
> Looks like there are several issues:
> 
>     * The spark mod appears to be corrupt. A reinstall ought to help.
> 
>     * Your advanced rocketry `planetDefs.xml` is corrupt, go into your world folder under `advRocketry` and delete the `planetDefs.xml` while you're not in the game.
same error code was given

**Comment by HeatherComputer** [comment]
I'd suggest following the bot's advice.
