### ISSUE TITLE
Game crashes after trying to render xu2 machine block

### ISSUE THREAD

**Issue by DefinitelyNotAPyramidScheme** [EnigmaticaModpacks/Enigmatica2Expert#2197]
### Modpack Version

1.12.2-14.23.5.2860

### Describe your issue.

I'm currently trying to craft an RFTools Tier 1 Crafter, but the game keeps crashing constantly.

### Crash Report

https://gist.github.com/DefinitelyNotAPyramidScheme/dc3db64c17008086a2ed8a5f37f4e249

### Latest Log

https://gist.github.com/DefinitelyNotAPyramidScheme/bf57f8216a48e1a9a6803870375f1679

### Have you modified the modpack?

Yes

### User Modifications

foamfix configs: fasterAnimation, unpackBakedQuads, parallelModelBaking

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

zeron5964

**Comment by MommyHeather** [comment]
> foamfix configs: fasterAnimation, unpackBakedQuads, parallelModelBaking

Can you reproduce the issue with those set to default?

**Comment by DefinitelyNotAPyramidScheme** [comment]
> > foamfix configs: fasterAnimation, unpackBakedQuads, parallelModelBaking
> 
> Can you reproduce the issue with those set to default?

Yes, it still crashes, those were supposed to be fixes for the problem

**Comment by NielsPilgaard** [comment]
Can you use a regular crafting table to craft it?
