### ISSUE TITLE
Mekanism 10 backport

### ISSUE THREAD

**Issue by lisekilis** [EnigmaticaModpacks/Enigmatica2Expert#2198]
### URL

https://www.curseforge.com/minecraft/mc-mods/mekanism-ce-unofficial

### Why would you like the mod added?

To bring the awsome features of mekanism 10 to E2E and potentially add some more mid/late game content

**Comment by MommyHeather** [comment]
Ultimately, I don't see this happening (though it could be cool) as it's *lot* of work and e2e is already in an eol state where updates are pretty much just small qol / bug fixes.

**Comment by NielsPilgaard** [comment]
I'm afraid I don't see this happening, as Heather said it's a ton of work for a pack we don't actively work on.
