### ISSUE TITLE
I don't understand why ore excavation is included in the pack

### ISSUE THREAD

**Issue by nonatee** [EnigmaticaModpacks/Enigmatica2Expert#2199]
### Describe your suggestion

Ore excavator mod should be removed

### Why would you like this added/changed?

Ore excavation being in the pack makes like a good 50% of material/modifier traits in tic be useless, i just dont see why this was included. I don't see the point in including it in an "expert" pack

**Comment by NielsPilgaard** [comment]
Ore Excavation is included to reduce the early game grind 😊
